# Generated by Django 5.1.4 on 2024-12-15 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelves.bookshelf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
