# Generated by Django 5.1.4 on 2024-12-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('completed', 'Completed')], default='not_started', max_length=50),
        ),
    ]
